In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns

In [5]:
import os
os.getcwd()

'c:\\Users\\Finn Case\\OneDrive\\Desktop\\Econ 430 Proj 1\\Econ_430_proj_1\\notebooks'

In [7]:
companies = pd.read_csv("../data/raw/us-companies.zip", sep=";")

In [8]:
companies.head()

,Ticker,SimFinId,Company Name,IndustryId,ISIN,End of financial year (month),Number Employees,Business Summary,Market,CIK,Main Currency
0,NaN,20095034,NaN,NaN,NaN,NaN,NaN,NaN,us,1986247.0,USD
1,NaN,20215308,NaN,NaN,NaN,NaN,NaN,NaN,us,2033535.0,USD
2,NaN,20619455,"CoreWeave, Inc.",NaN,NaN,12.0,NaN,NaN,us,1769628.0,USD
3,NaN,18692750,NaN,NaN,NaN,NaN,NaN,NaN,us,1997711.0,USD
4,NaN,18847915,NaN,NaN,NaN,NaN,NaN,NaN,us,1769731.0,USD

In [10]:
companies.shape
companies.describe()

,SimFinId,IndustryId,End of financial year (month),Number Employees,CIK
count,6.593000e+03,6278.000000,6558.000000,5.755000e+03,6.581000e+03
mean,7.131233e+06,104048.265053,10.993901,7.514445e+03,1.274917e+06
std,6.884316e+06,2818.969285,2.645427,3.140868e+04,5.286397e+05
min,1.800000e+01,100001.000000,1.000000,0.000000e+00,0.000000e+00
25%,6.661000e+05,101004.000000,12.000000,1.360000e+02,9.311480e+05
50%,6.767475e+06,104002.000000,12.000000,8.800000e+02,1.406234e+06
75%,1.244441e+07,106002.000000,12.000000,3.700000e+03,1.703157e+06
max,2.080346e+07,111001.000000,12.000000,1.298000e+06,2.079173e+06

In [21]:
companies.columns
companies.dtypes
companies.isna().sum()

Ticker                             40
SimFinId                            0
Company Name                       36
IndustryId                        315
ISIN                             1202
End of financial year (month)      35
Number Employees                  838
Business Summary                  299
Market                              0
CIK                                12
Main Currency                       0
dtype: int64

In [22]:
companies.shape

(6593, 11)

In [29]:
companies['IndustryId'].isnull().sum() / companies.shape[0] * 100

np.float64(4.777794630668891)

In [ ]:
# IndustryID is a usable column, only 4.8% is null

In [47]:
income = pd.read_csv('../data/raw/us-income-quarterly.zip',sep=';')

In [48]:
income.head()

,Ticker,SimFinId,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Non-Operating Income (Loss),"Interest Expense, Net","Pretax Income (Loss), Adj.",Abnormal Gains (Losses),Pretax Income (Loss),"Income Tax (Expense) Benefit, Net",Income (Loss) from Continuing Operations,Net Extraordinary Gains (Losses),Net Income,Net Income (Common)
0,A,45846,USD,2021,Q1,2021-01-31,2021-03-02,2022-03-03,306000000.0,309000000.0,...,-16000000.0,-19000000.0,312000000.0,NaN,312000000,-24000000.0,288000000,NaN,288000000,288000000
1,A,45846,USD,2021,Q2,2021-04-30,2021-06-01,2022-05-31,306000000.0,306000000.0,...,-15000000.0,-19000000.0,273000000.0,NaN,273000000,-57000000.0,216000000,NaN,216000000,216000000
2,A,45846,USD,2021,Q3,2021-07-31,2021-09-01,2022-09-01,303000000.0,306000000.0,...,-9000000.0,-21000000.0,327000000.0,NaN,327000000,-63000000.0,264000000,NaN,264000000,264000000
3,A,45846,USD,2021,Q4,2021-10-31,2021-12-17,2022-09-01,305000000.0,307000000.0,...,53000000.0,-20000000.0,448000000.0,NaN,448000000,-6000000.0,442000000,NaN,442000000,442000000
4,A,45846,USD,2022,Q1,2022-01-31,2022-03-03,2023-03-03,301000000.0,303000000.0,...,-57000000.0,-20000000.0,319000000.0,NaN,319000000,-36000000.0,283000000,NaN,283000000,283000000

In [49]:
income.shape

(47685, 28)

In [50]:
income.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date', 'Shares (Basic)',
       'Shares (Diluted)', 'Revenue', 'Cost of Revenue', 'Gross Profit',
       'Operating Expenses', 'Selling, General & Administrative',
       'Research & Development', 'Depreciation & Amortization',
       'Operating Income (Loss)', 'Non-Operating Income (Loss)',
       'Interest Expense, Net', 'Pretax Income (Loss), Adj.',
       'Abnormal Gains (Losses)', 'Pretax Income (Loss)',
       'Income Tax (Expense) Benefit, Net',
       'Income (Loss) from Continuing Operations',
       'Net Extraordinary Gains (Losses)', 'Net Income',
       'Net Income (Common)'],
      dtype='str')

In [51]:
income.isnull().sum()

Ticker                                          0
SimFinId                                        0
Currency                                        0
Fiscal Year                                     0
Fiscal Period                                   0
Report Date                                     0
Publish Date                                    0
Restated Date                                   0
Shares (Basic)                                325
Shares (Diluted)                              389
Revenue                                      5100
Cost of Revenue                             10240
Gross Profit                                10230
Operating Expenses                             90
Selling, General & Administrative            2120
Research & Development                      24320
Depreciation & Amortization                 28174
Operating Income (Loss)                         3
Non-Operating Income (Loss)                   491
Interest Expense, Net                        6061
Pretax Income (Loss), Adj.                      2
Abnormal Gains (Losses)                     21595
Pretax Income (Loss)                            0
Income Tax (Expense) Benefit, Net            9844
Income (Loss) from Continuing Operations        0
Net Extraordinary Gains (Losses)            44903
Net Income                                      0
Net Income (Common)                             0
dtype: int64

In [53]:
income = income[[
    'Ticker',
    'SimFinId',
    'Currency',
    'Fiscal Year',
    'Fiscal Period',
    'Report Date',
    'Publish Date',
    'Revenue',
    'Gross Profit',
    'Operating Income (Loss)',
    'Depreciation & Amortization',
    'Interest Expense, Net',
    'Pretax Income (Loss)',
    'Income Tax (Expense) Benefit, Net',
    'Net Income'
]]

In [55]:
balance = pd.read_csv("../data/raw/us-balance-quarterly.zip",sep=";")

In [57]:
balance.head()

,Ticker,SimFinId,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Short Term Debt,Total Current Liabilities,Long Term Debt,Total Noncurrent Liabilities,Total Liabilities,Share Capital & Additional Paid-In Capital,Treasury Stock,Retained Earnings,Total Equity,Total Liabilities & Equity
0,A,45846,USD,2021,Q1,2021-01-31,2021-03-02,2021-03-02,306000000.0,309000000.0,...,314000000.0,1.687000e+09,2.185000e+09,3.183000e+09,4.870000e+09,5.269000e+09,NaN,4000000.0,4.804000e+09,9674000000
1,A,45846,USD,2021,Q2,2021-04-30,2021-06-01,2021-06-01,306000000.0,306000000.0,...,205000000.0,1.758000e+09,2.727000e+09,3.830000e+09,5.588000e+09,5.274000e+09,NaN,-12000000.0,4.810000e+09,10398000000
2,A,45846,USD,2021,Q3,2021-07-31,2021-09-01,2021-09-01,303000000.0,306000000.0,...,130000000.0,1.724000e+09,2.728000e+09,3.821000e+09,5.545000e+09,5.310000e+09,NaN,90000000.0,4.946000e+09,10491000000
3,A,45846,USD,2021,Q4,2021-10-31,2021-12-17,2022-12-21,305000000.0,307000000.0,...,NaN,1.708000e+09,2.729000e+09,3.608000e+09,5.316000e+09,5.323000e+09,NaN,348000000.0,5.389000e+09,10705000000
4,A,45846,USD,2022,Q1,2022-01-31,2022-03-03,2022-03-03,301000000.0,303000000.0,...,NaN,1.584000e+09,2.730000e+09,3.589000e+09,5.173000e+09,5.293000e+09,NaN,159000000.0,5.154000e+09,10327000000

In [58]:
balance.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date', 'Shares (Basic)',
       'Shares (Diluted)', 'Cash, Cash Equivalents & Short Term Investments',
       'Accounts & Notes Receivable', 'Inventories', 'Total Current Assets',
       'Property, Plant & Equipment, Net',
       'Long Term Investments & Receivables', 'Other Long Term Assets',
       'Total Noncurrent Assets', 'Total Assets', 'Payables & Accruals',
       'Short Term Debt', 'Total Current Liabilities', 'Long Term Debt',
       'Total Noncurrent Liabilities', 'Total Liabilities',
       'Share Capital & Additional Paid-In Capital', 'Treasury Stock',
       'Retained Earnings', 'Total Equity', 'Total Liabilities & Equity'],
      dtype='str')

In [59]:
balance.isnull().sum()

Ticker                                                 0
SimFinId                                               0
Currency                                               0
Fiscal Year                                            0
Fiscal Period                                          0
Report Date                                            0
Publish Date                                           0
Restated Date                                          0
Shares (Basic)                                       322
Shares (Diluted)                                     386
Cash, Cash Equivalents & Short Term Investments      164
Accounts & Notes Receivable                         9934
Inventories                                        21612
Total Current Assets                                   5
Property, Plant & Equipment, Net                    3237
Long Term Investments & Receivables                36634
Other Long Term Assets                              1564
Total Noncurrent Assets                              303
Total Assets                                           0
Payables & Accruals                                  158
Short Term Debt                                    22711
Total Current Liabilities                             58
Long Term Debt                                     13260
Total Noncurrent Liabilities                        1380
Total Liabilities                                      9
Share Capital & Additional Paid-In Capital           652
Treasury Stock                                     31523
Retained Earnings                                   1882
Total Equity                                           5
Total Liabilities & Equity                             0
dtype: int64

In [60]:
balance = balance[[
    'Ticker',
    'SimFinId',
    'Currency',
    'Fiscal Year',
    'Fiscal Period',
    'Report Date',
    'Publish Date',
    'Cash, Cash Equivalents & Short Term Investments',
    'Short Term Debt',
    'Long Term Debt',
    'Total Assets',
    'Total Liabilities',
    'Total Equity'
]]

In [61]:
cashflow = pd.read_csv(
    "../data/raw/us-cashflow-quarterly.zip",
    sep=";"
)

In [62]:
cashflow.shape

(47687, 28)

In [63]:
cashflow.head()

,Ticker,SimFinId,Currency,Fiscal Year,Fiscal Period,Report Date,Publish Date,Restated Date,Shares (Basic),Shares (Diluted),...,Net Cash from Operating Activities,Change in Fixed Assets & Intangibles,Net Change in Long Term Investment,Net Cash from Acquisitions & Divestitures,Net Cash from Investing Activities,Dividends Paid,Cash from (Repayment of) Debt,Cash from (Repurchase of) Equity,Net Cash from Financing Activities,Net Change in Cash
0,A,45846,USD,2021,Q1,2021-01-31,2021-03-02,2022-03-03,306000000.0,309000000.0,...,238000000.0,-41000000.0,NaN,NaN,-42000000.0,-59000000.0,134000000.0,-319000000.0,-316000000.0,-111000000
1,A,45846,USD,2021,Q2,2021-04-30,2021-06-01,2022-03-03,306000000.0,306000000.0,...,472000000.0,-31000000.0,NaN,-547000000.0,-587000000.0,-59000000.0,427000000.0,-194000000.0,166000000.0,51000000
2,A,45846,USD,2021,Q3,2021-07-31,2021-09-01,2022-05-31,303000000.0,306000000.0,...,334000000.0,-54000000.0,NaN,0.0,-61000000.0,-59000000.0,-75000000.0,-87000000.0,-222000000.0,48000000
3,A,45846,USD,2021,Q4,2021-10-31,2021-12-17,2022-09-01,305000000.0,307000000.0,...,441000000.0,-61000000.0,12000000.0,0.0,-59000000.0,-59000000.0,-130000000.0,-133000000.0,-324000000.0,55000000
4,A,45846,USD,2022,Q1,2022-01-31,2022-03-03,2023-03-03,301000000.0,303000000.0,...,255000000.0,-75000000.0,NaN,NaN,-76000000.0,-63000000.0,0.0,-420000000.0,-546000000.0,-371000000

In [64]:
cashflow.columns

Index(['Ticker', 'SimFinId', 'Currency', 'Fiscal Year', 'Fiscal Period',
       'Report Date', 'Publish Date', 'Restated Date', 'Shares (Basic)',
       'Shares (Diluted)', 'Net Income/Starting Line',
       'Depreciation & Amortization', 'Non-Cash Items',
       'Change in Working Capital', 'Change in Accounts Receivable',
       'Change in Inventories', 'Change in Accounts Payable',
       'Change in Other', 'Net Cash from Operating Activities',
       'Change in Fixed Assets & Intangibles',
       'Net Change in Long Term Investment',
       'Net Cash from Acquisitions & Divestitures',
       'Net Cash from Investing Activities', 'Dividends Paid',
       'Cash from (Repayment of) Debt', 'Cash from (Repurchase of) Equity',
       'Net Cash from Financing Activities', 'Net Change in Cash'],
      dtype='str')

In [65]:
cashflow.isna().sum()

Ticker                                           0
SimFinId                                         0
Currency                                         0
Fiscal Year                                      0
Fiscal Period                                    0
Report Date                                      0
Publish Date                                     0
Restated Date                                    0
Shares (Basic)                                 325
Shares (Diluted)                               389
Net Income/Starting Line                       457
Depreciation & Amortization                   2503
Non-Cash Items                                 484
Change in Working Capital                      413
Change in Accounts Receivable                47242
Change in Inventories                        47367
Change in Accounts Payable                   47296
Change in Other                              47076
Net Cash from Operating Activities               4
Change in Fixed Assets & Intangibles          4120
Net Change in Long Term Investment           30691
Net Cash from Acquisitions & Divestitures    32054
Net Cash from Investing Activities            1548
Dividends Paid                               30857
Cash from (Repayment of) Debt                12387
Cash from (Repurchase of) Equity             11052
Net Cash from Financing Activities            1040
Net Change in Cash                               0
dtype: int64

In [66]:
cashflow = cashflow[
    [
        'Ticker',
        'SimFinId',
        'Currency',
        'Fiscal Year',
        'Fiscal Period',
        'Report Date',
        'Publish Date',
        'Net Income/Starting Line',
        'Depreciation & Amortization',
        'Net Cash from Operating Activities',
        'Change in Fixed Assets & Intangibles',
        'Net Cash from Investing Activities',
        'Cash from (Repayment of) Debt',
        'Net Cash from Financing Activities',
        'Net Change in Cash'
    ]
]

In [67]:
prices = pd.read_csv(
    "../data/raw/us-shareprices-daily.zip",
    sep=";"
)

In [68]:
prices.shape

(6217940, 11)

In [69]:
prices.columns

Index(['Ticker', 'SimFinId', 'Date', 'Open', 'High', 'Low', 'Close',
       'Adj. Close', 'Volume', 'Dividend', 'Shares Outstanding'],
      dtype='str')

In [70]:
prices.head()

,Ticker,SimFinId,Date,Open,High,Low,Close,Adj. Close,Volume,Dividend,Shares Outstanding
0,A,45846,2020-11-05,110.57,111.93,109.67,110.34,106.04,1143082,NaN,306000000.0
1,A,45846,2020-11-06,110.76,113.35,110.33,112.54,108.16,1036556,NaN,306000000.0
2,A,45846,2020-11-09,116.16,117.50,112.39,112.50,108.12,2178042,NaN,306000000.0
3,A,45846,2020-11-10,112.82,112.91,108.99,110.20,105.91,2124829,NaN,306000000.0
4,A,45846,2020-11-11,111.14,111.79,108.84,109.41,105.15,1792823,NaN,306000000.0

In [72]:
prices.isna().sum()

Ticker                    816
SimFinId                    0
Date                        0
Open                        0
High                        0
Low                         0
Close                       0
Adj. Close                  0
Volume                      0
Dividend              6180595
Shares Outstanding     438299
dtype: int64

In [73]:
prices['Date'].min()

'2020-11-05'

In [74]:
prices['Date'].max()

'2025-10-09'

In [75]:
prices['Date'].dtype

In [76]:
prices['Date'] = pd.to_datetime(prices['Date'])

In [77]:
prices['Date'].dtype

dtype('<M8[us]')

In [78]:
income['Report Date'] = pd.to_datetime(income['Report Date'])
income['Publish Date'] = pd.to_datetime(income['Publish Date'])

balance['Report Date'] = pd.to_datetime(balance['Report Date'])
balance['Publish Date'] = pd.to_datetime(balance['Publish Date'])

cashflow['Report Date'] = pd.to_datetime(cashflow['Report Date'])
cashflow['Publish Date'] = pd.to_datetime(cashflow['Publish Date'])

In [79]:
income['Publish Date'].min(), income['Publish Date'].max()

(Timestamp('2009-01-01 00:00:00'), Timestamp('2026-07-17 00:00:00'))

In [80]:
balance['Publish Date'].min(), balance['Publish Date'].max()

(Timestamp('2009-01-01 00:00:00'), Timestamp('2026-07-17 00:00:00'))

In [81]:
cashflow['Publish Date'].min(), cashflow['Publish Date'].max()

(Timestamp('2009-01-01 00:00:00'), Timestamp('2026-07-17 00:00:00'))